### PR TITLE
lovely printer

### PR DESCRIPTION
**Pull request by spyoungtech**
Love is in the air. Is it in your Python, too?

TODO:

- [ ] make a `__main__` that accepts input from stdin
- [ ] fill character for whitespace?
- [ ] golf it
- [ ] setup.py

From the README:

# Lovely Printer

The idea here is simple: You have a program that prints things. Now you can have a program that prints things in the shape of a heart!

## Usage

The main usage is via context manager that temporarily overrides the builtin `print`. 
That is, you should be able to use this with any existing program that uses `print`! How lovely!

Suppose you have your normal boring program

```python
# my_program.py
def main():
    print('This is just an example')
```
Make it lovely like so

```python
from lovely_printer import lovely_print
from my_program import main

with lovely_print():
    main()
# then print returns to normal
print("Isn't that lovely?")
```

Then you should see the output something like

```
 This    is 
j    u s    t
      a     n
           e
  x       a
   m     p
    l   e
     T h
      i

Isn't that lovely?
```

### CODE REVIEW

**Comment by lemonsaurus** [comment]
I love this one so much.

**Comment by skrungly** [comment]
oh cool! i'm interested to see what else could be done with this idea, actually. the code is beautiful too. if you want, you can make a separate file in the PR where all of the code is made weird and esoteric (to fit with the rest of the repo :D)

**Comment by spyoungtech** [comment]
Yeah, I was thinking of a one-liner implementation that uses a class for the context manager. Something like

```
lovely_printer = type('',(),dict(__enter__=lambda s:s, __exit__=lambda s:s))()
```
(inspired by David Beazley's [flail](https://github.com/dabeaz/flail/blob/master/flail/__init__.py))

Should be doable, and very diabolical.  Not sure if I'll have time to get around to it, but also happy to accept contributions :P

**Comment by spyoungtech** [comment]
probably won't get around to changes I want. Feel free to just merge

**Pull request merged**
